### ISSUE TITLE
review the course website for inconsistencies

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/paper-rcourse#31]
review the course website and check for inconsistencies with the Github repo, verify the content is up to date

**Comment by lwjohnst86** [comment]
Multiple eyes to look at this would be helpful, so if anyone else wants to assign themselves, dooo iittt!

**Comment by lwjohnst86** [comment]
Done :) If anyone wants to take a look at the website, let me know. Otherwise I will start the process of sending a release/update the version
