### ISSUE TITLE
List of consistent and correct spelling, tense, terminology for JOSE publication

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/paper-rcourse#44]
We can edit the list and bold the option we will use in the end and checkmark if we have checked for consistency and changed any outliers. Also feel free to include any variants you've noticed that we should change.

- [x] modeling vs **modelling**
- [ ] lecture vs lesson 
- [x] course vs module vs learning module
- [ ] Tense: Present, Past 
  - consistent within sections since teaching experience will be describing what happened?, the rest seems to be in the present, (active??) voice
- [x] ~coding vs programming (is this necessary?)~
- [x] markdown vs **R Markdown** vs R-markdown vs rmarkdown etc.
- [x] **live-coding** vs live coding
- [x] **principal** component analysis (look for principle)
- [x] **GitHub** (look for Github)

**Comment by QuLogic** [comment]
Should [live coding](https://en.wikipedia.org/wiki/Live_coding) be hyphenated? (The link's not exactly the same thing, but it's about the grammar...)

**Comment by SaraMati** [comment]
- I vote for **lecture** vs lesson 
- we can start with "learning module" and mention that the learning module we are submitting is a course and then continue with course 
- coding and programming can be used interchangeably (it's advised to use such synonyms to avoid repetition in writing)

**Comment by lwjohnst86** [comment]
Not sure I agree with lecture, since lecture tends to give the impression of instructors talking for the entire session while students passively listen. I prefer **lesson**.

I like learning module, with submodules (the multi-lesson broader topics).

**Comment by joelostblom** [comment]
I checked `modelling` and `live-coding` in Luke's PR as of now. Can check active voice after the next update if needed.

**Comment by lwjohnst86** [comment]
I think all editing has been done :)
