### ISSUE TITLE
Do we need/want a professor involved?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/paper-rcourse#6]
Candidates would be Martin, Asher, or Christie (mozilla). Since Christie is the original author of the curriculum we based our course on, we might want to inform her that we write a paper and potentially extend an invitation. I think it depends on how much we go for "our experience" vs "general ideas on course like this" (which we discuss in #1).

**Comment by lwjohnst86** [comment]
Yes, it might really depend on how we frame it. Let's first get an stronger idea on what the flow/content will be, then decide if we need to bring on others eg. Christie

**Comment by mbonsma** [comment]
Sounds good. The other reason to have a prof along would be for someone to pay for journal submission.

**Comment by lwjohnst86** [comment]
Let's shelve this idea for later. I don't think we will need one.
