### ISSUE TITLE
Suggest an editor

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/paper-rcourse#69]
As part of the submission, we get to suggest an editor. There are two (Tania Allard and Pjotr Prins) that are listed as topic editors for reproducible science on the [editorial board](https://joss.theoj.org/about#editorial_board). There are a few others that mention reproducible science in their blurbs (Melissa Gymrek, Karthik Ram (also an ecologist), Ariel Rokem), so we could pick one of those five. 

Does anyone have a preference or know of anyone on the list that would be a good choice? I only recognize Yo Yehudi from the Mozilla mentorship programs, but I did not really interact with her much there. I am leaning towards Karthik because he is also an ecologist, but Melissa or Tania also seem like good choices.

**Comment by lwjohnst86** [comment]
I'll include Karthik as the suggested editor. Thanks for looking into this.

**Comment by lwjohnst86** [comment]
The link you provided was from JOSS, not JOSE. 

There are two editors that seem relevant: Juan Klopper and Tracy Teal. I think I'll choose Tracy Teal, since she is also part of Data Carpentry.

**Comment by joelostblom** [comment]
Doh! Sorry about that clumsy mistake. Tracy Teal looks suitable!
