### ISSUE TITLE
Add DOI to all references

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/paper-rcourse#75]
As per https://github.com/UofTCoders/rcourse/issues/292.

Can someone please assign themselves this issue and deal with the DOI addition to the `.bib` file.

**Comment by mbonsma** [comment]
@SaraMati, I can do this today unless you're planning on doing it soon!

**Comment by SaraMati** [comment]
I planned to do it on Thursday morning, feel free to do it earlier

**Comment by SaraMati** [comment]
Finished with what I could find. 

The below items don't have DOI, or I couldn't find:

Teaching tech together
Project-based learning: A bridge just far enough
and packages:
R, tidyverse, dplyr, knitr, rmarkdown, psych, car, MuMIn
(for these I checked both using citation command in R and searching the web)

**Comment by lwjohnst86** [comment]
That's fine, thanks :) Submit a PR and we'll merge in! :)

**Comment by QuLogic** [comment]
We can probably add the http://teachtogether.tech/ site to [Teaching tech together](https://github.com/gvwilson/teachtogether.tech/blob/master/CITATION.md). There's no DOI there in the sample citation either.

**Comment by QuLogic** [comment]
There are [3 citations for knitr](https://cran.r-project.org/web/packages/knitr/citation.html) and [2 citations for rmarkdown](https://cran.r-project.org/web/packages/rmarkdown/citation.html), but we only cite one of them. I guess we should cite all of them?

**Comment by SaraMati** [comment]
I'd say we refer to them where we mention we used these packages, so the 'manual' citation suffices.

**Comment by SaraMati** [comment]
added the URL for teach together in both the paper and the rcourse repo
