### ISSUE TITLE
Update paper from this repo to the rcourse repo

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/paper-rcourse#76]
So that we can address the comments in https://github.com/UofTCoders/rcourse/issues/292.

**Comment by lwjohnst86** [comment]
only thing needs updating is the `paper.bib` file, so whenever someone does it, move the bib file over and close this issue :)

**Comment by SaraMati** [comment]
The below items don't have DOI, or I couldn't find: 
- Teaching tech together
- Project-based learning: A bridge just far enough
and packages: 
 R, tidyverse, dplyr, knitr, rmarkdown, psych, car, MuMIn 
(for these I checked both using citation command in R and searching the web)

you may want to check too, before updating the course repo

**Comment by lwjohnst86** [comment]
Yea, I didn't find any for those either.
